language: java
jdk:
    openjdk11
install: true
before_install:
  - nvm ls-remote
  - nvm install 12.6.0
  - nvm use 12.6.0
  - npm install -g @angular/cli@latest
stages:
  - name: test
  - name: build
  - name: deliver
    if: branch = develop
  - name: deploy
    if: branch = master
jobs:
  include:
      - stage: test
        script:
          - cd backend
          - chmod +x mvnw
          - mvn test
      - stage: build
        script:
         - cd frontend
         - npm i
         - ng build --prod
         - cd ..
         - mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
      - stage: deliver
        script:
          - cd backend
          - mvn package -Dmaven.test.skip=true
          - docker build -t studentproject/ocado-tim-backend:latest .
          - cd ../auth_server
          - mvn package -Dmaven.test.skip=true
          - docker build -t studentproject/ocado-tim-oauth:latest .
          - cd ../frontend
          - npm install -f
          - node -v
          - npm install @types/node --save-dev
          - npm run build
          - docker build -t studentproject/ocado-tim-frontend:latest .
          - docker login -u "studentproject" -p "$DOCKER_PASSWORD"
          - docker push studentproject/ocado-tim-frontend:latest
          - docker push studentproject/ocado-tim-backend:latest
          - docker push studentproject/ocado-tim-oauth:latest
      - stage: deploy
        script:
          - curl https://cli-assets.heroku.com/install-standalone.sh | sh
          - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
          - cd backend
          - mvn package -Dmaven.test.skip=true
          - docker build -t registry.heroku.com/studentproject-tim-backend/web -f Dockerfile.prod .
          - docker push registry.heroku.com/studentproject-tim-backend/web
          - /usr/local/bin/heroku container:release web -a studentproject-tim-backend
          - cd ../auth_server
          - mvn package -Dmaven.test.skip=true
          - docker build -t registry.heroku.com/studentproject-tim-oauth/web -f Dockerfile .
          - docker push registry.heroku.com/studentproject-tim-oauth/web
          - /usr/local/bin/heroku container:release web -a studentproject-tim-oauth
          - cd ../frontend
          - npm install
          - npm install @types/node --save-dev
          - ng build --prod
          - docker build -t registry.heroku.com/studentproject-tim-frontend/web -f Dockerfile.prod .
          - docker push registry.heroku.com/studentproject-tim-frontend/web
          - /usr/local/bin/heroku container:release web -a studentproject-tim-frontend
